"""
Atomic Orbital Viewer
=====================

An educational tool for a single atom.

  • "AO basis functions" tab — pick an element and a basis set, then browse
    the contracted Gaussian basis functions the basis defines and render each
    one on a single atom at the origin (evaluated directly, no SCF).

  • "STO / GTO playground" tab — tune a Slater-type orbital and a sum of
    Gaussians and watch the Gaussians combine to mimic it, which is exactly
    what an STO-nG basis set does.
"""

import numpy as np
import streamlit as st
import py3Dmol

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

from pyscf import gto
from pyscf.dft import numint


BOHR = 0.52917721092  # Angstrom per Bohr

# Elements offered in the picker. Z is just (index + 1).
ELEMENTS = [
    "H", "He",
    "Li", "Be", "B", "C", "N", "O", "F", "Ne",
    "Na", "Mg", "Al", "Si", "P", "S", "Cl", "Ar",
    "K", "Ca",
    "Sc", "Ti", "V", "Cr", "Mn", "Fe", "Co", "Ni", "Cu", "Zn",
    "Ga", "Ge", "As", "Se", "Br", "Kr",
]

BASIS_SETS = [
    "STO-3G",
    "3-21G",
    "6-31G",
    "6-31G*",
    "6-311G**",
    "cc-pVDZ",
    "cc-pVTZ",
    "def2-SVP",
    "def2-TZVP",
    "Custom…",
]


# ----------------------------------------------------------------------
# PySCF helpers (cached so switching orbitals stays snappy)
# ----------------------------------------------------------------------

@st.cache_resource(show_spinner=False)
def build_atom(element, basis):
    """Single atom at the origin. spin is set only to satisfy PySCF's
    parity check; eval_ao does not depend on it."""
    z = ELEMENTS.index(element) + 1
    return gto.M(
        atom=f"{element} 0.0 0.0 0.0",
        basis=basis,
        unit="Bohr",
        spin=z % 2,
        verbose=0,
    )


def _eval(mol, points, ao_idx):
    return numint.eval_ao(mol, points)[:, ao_idx]


@st.cache_data(show_spinner=False)
def estimate_half_width(element, basis, ao_idx, iso_frac):
    """Coarse scan to find how far the orbital extends, so the render
    box auto-fits diffuse (large n, small exponent) orbitals."""
    mol = build_atom(element, basis)
    max_half, n = 18.0, 29
    g = np.linspace(-max_half, max_half, n)
    gx, gy, gz = np.meshgrid(g, g, g, indexing="ij")
    pts = np.column_stack([gx.ravel(), gy.ravel(), gz.ravel()])

    vals = _eval(mol, pts, ao_idx)
    amax = np.abs(vals).max()
    if amax == 0.0:
        return max_half

    mask = np.abs(vals) >= iso_frac * amax
    half = np.abs(pts[mask]).max() if mask.any() else max_half
    return float(min(max_half, half * 1.25 + 1.5))


@st.cache_data(show_spinner=False)
def compute_volume(element, basis, ao_idx, resolution, half):
    """Evaluate the chosen orbital on a cubic grid of half-width `half`."""
    mol = build_atom(element, basis)
    axis = np.linspace(-half, half, resolution)
    gx, gy, gz = np.meshgrid(axis, axis, axis, indexing="ij")
    pts = np.column_stack([gx.ravel(), gy.ravel(), gz.ravel()])

    vol = _eval(mol, pts, ao_idx).reshape(resolution, resolution, resolution)
    return vol, axis


# ----------------------------------------------------------------------
# Gaussian cube file (string) for py3Dmol, coordinates in Bohr
# ----------------------------------------------------------------------

def make_cube_string(element, values, axis):
    n = len(axis)
    origin = axis[0]
    d = axis[1] - axis[0]
    z = ELEMENTS.index(element) + 1

    lines = [
        "Atomic orbital",
        "Generated by Atomic Orbital Viewer",
        f"{1:5d}{origin:12.6f}{origin:12.6f}{origin:12.6f}",
        f"{n:5d}{d:12.6f}{0.0:12.6f}{0.0:12.6f}",
        f"{n:5d}{0.0:12.6f}{d:12.6f}{0.0:12.6f}",
        f"{n:5d}{0.0:12.6f}{0.0:12.6f}{d:12.6f}",
        f"{z:5d}{float(z):12.6f}{0.0:12.6f}{0.0:12.6f}{0.0:12.6f}",
    ]

    flat = values.ravel(order="C")
    for i in range(0, len(flat), 6):
        chunk = flat[i:i + 6]
        lines.append(" ".join(f"{v:13.5e}" for v in chunk))

    return "\n".join(lines)


# ----------------------------------------------------------------------
# UI
# ----------------------------------------------------------------------

st.set_page_config(page_title="Atomic Orbital Viewer", layout="centered")
st.title("Atomic Orbital Viewer")

tab_ao, tab_play = st.tabs(["AO basis functions", "STO / GTO playground"])


# ============================ Tab 1: basis functions ===================

with tab_ao:
    st.caption(
        "Pick an element and a basis set, then explore the atomic orbitals "
        "that basis defines."
    )

    c1, c2 = st.columns(2)
    with c1:
        element = st.selectbox("Element", ELEMENTS, index=ELEMENTS.index("C"))
    with c2:
        basis_choice = st.selectbox(
            "Basis set", BASIS_SETS, index=BASIS_SETS.index("cc-pVDZ"))

    basis = basis_choice
    if basis_choice == "Custom…":
        basis = st.text_input("Custom basis name (as recognised by PySCF)", "6-31G")

    try:
        mol = build_atom(element, basis)
    except Exception as e:
        st.error(
            f"Could not build {element} with basis '{basis}'. "
            f"This basis set may not cover this element.\n\n{e}"
        )
    else:
        raw_labels = mol.ao_labels()
        nao = mol.nao_nr()

        def clean_label(i):
            # "0 C 2px" -> "2px"
            parts = raw_labels[i].split(None, 2)
            return parts[2] if len(parts) == 3 else raw_labels[i]

        st.write(f"**{element} / {basis}** defines **{nao}** atomic orbitals.")

        ao_idx = st.selectbox(
            "Atomic orbital",
            range(nao),
            format_func=lambda i: f"{i:>3}:  {clean_label(i)}",
        )

        iso_frac = st.slider(
            "Isosurface level (fraction of peak amplitude)",
            min_value=0.001, max_value=0.10, value=0.05, step=0.001, format="%.3f",
            help="Lower = larger, fuzzier lobes; higher = tight cores around the peaks.",
        )

        with st.expander("Advanced"):
            resolution = st.slider("Grid resolution", 30, 90, 60, step=5)
            auto_box = st.checkbox("Auto-fit box to orbital", value=True)
            manual_half = st.slider("Box half-width (Bohr)", 3.0, 18.0, 8.0, step=0.5)

        with st.spinner("Evaluating orbital…"):
            if auto_box:
                half = estimate_half_width(element, basis, ao_idx, iso_frac)
            else:
                half = manual_half
            volume, axis = compute_volume(element, basis, ao_idx, resolution, half)

        absmax = float(np.max(np.abs(volume)))
        iso = iso_frac * absmax
        cube_str = make_cube_string(element, volume, axis)

        view = py3Dmol.view(width=720, height=560)
        view.addModel(f"1\n\n{element} 0.0 0.0 0.0\n", "xyz")
        view.setStyle({}, {"sphere": {"scale": 0.3}})
        view.addVolumetricData(
            cube_str, "cube", {"isoval": iso, "color": "blue", "opacity": 0.85})
        view.addVolumetricData(
            cube_str, "cube", {"isoval": -iso, "color": "red", "opacity": 0.85})
        view.zoomTo()
        st.components.v1.html(view._make_html(), height=580, width=740)

        st.caption(
            f"Showing **{clean_label(ao_idx)}** · box half-width "
            f"{half:.1f} Bohr · peak amplitude {absmax:.2e} · "
            f"blue = positive phase, red = negative phase."
        )


# ============================ Tab 2: STO / GTO playground ==============

with tab_play:
    st.caption(
        "A Slater-type orbital (STO), e^(−ζr), is the 'ideal' shape of a 1s "
        "orbital but is awkward to integrate, so basis sets approximate it with "
        "a sum of Gaussians (GTOs). Tune the Gaussians and watch them combine — "
        "this is exactly what an STO-nG basis does."
    )

    # Textbook STO-nG expansions of a 1s Slater (ζ = 1):
    # (normalised-primitive exponents α and contraction coefficients c)
    STO_NG = {
        1: ([0.270950], [1.000000]),
        2: ([0.851819, 0.151623], [0.430129, 0.678914]),
        3: ([2.227660, 0.405771, 0.109818], [0.154329, 0.535328, 0.444635]),
    }
    NMAX = 6

    # --- preset buttons (run BEFORE the sliders are instantiated) ---
    st.write("Load a textbook fit (ζ = 1):")
    b1, b2, b3 = st.columns(3)

    def load_preset(k):
        a, c = STO_NG[k]
        st.session_state["pg_zeta"] = 1.0
        st.session_state["pg_n"] = k
        for i in range(k):
            st.session_state[f"pg_la{i}"] = float(np.log10(a[i]))
            st.session_state[f"pg_c{i}"] = float(c[i])
        st.rerun()

    if b1.button("STO-1G", use_container_width=True):
        load_preset(1)
    if b2.button("STO-2G", use_container_width=True):
        load_preset(2)
    if b3.button("STO-3G", use_container_width=True):
        load_preset(3)

    # --- seed defaults (STO-3G, so the first view already looks good) ---
    default_a, default_c = STO_NG[3]
    st.session_state.setdefault("pg_zeta", 1.0)
    st.session_state.setdefault("pg_n", 3)
    for i in range(NMAX):
        st.session_state.setdefault(
            f"pg_la{i}",
            float(np.log10(default_a[i])) if i < 3 else float(np.log10(0.3)))
        st.session_state.setdefault(
            f"pg_c{i}", float(default_c[i]) if i < 3 else 0.20)

    zeta = st.slider("Slater exponent  ζ", 0.30, 3.00, step=0.05, key="pg_zeta")
    n = st.slider("Number of Gaussians", 1, NMAX, step=1, key="pg_n")

    alphas, coeffs = [], []
    for i in range(n):
        col_a, col_c = st.columns(2)
        la = col_a.slider(
            f"Gaussian {i + 1}:  log₁₀(α)", -1.5, 1.2, step=0.01, key=f"pg_la{i}")
        c = col_c.slider(
            f"coefficient  c{i + 1}", -1.0, 2.0, step=0.01, key=f"pg_c{i}")
        alphas.append(10.0 ** la)
        coeffs.append(c)

    # --- evaluate radial functions ---
    r = np.linspace(0.0, 6.0, 700)
    Ns = (zeta ** 3 / np.pi) ** 0.5
    sto = Ns * np.exp(-zeta * r)

    gto_sum = np.zeros_like(r)
    comps = []
    for a, c in zip(alphas, coeffs):
        Ng = (2.0 * a / np.pi) ** 0.75       # normalised 1s Gaussian
        comp = c * Ng * np.exp(-a * r ** 2)
        comps.append(comp)
        gto_sum += comp

    # scale-independent shape overlap (radial weight 4*pi*r^2)
    w = 4.0 * np.pi * r ** 2
    denom = np.sqrt(np.trapezoid(sto ** 2 * w, r) *
                    np.trapezoid(gto_sum ** 2 * w, r))
    overlap = float(np.trapezoid(sto * gto_sum * w, r) / denom) if denom else 0.0

    # --- plot ---
    fig, ax = plt.subplots(figsize=(6.4, 3.8))
    for comp in comps:
        ax.plot(r, comp, lw=1.0, alpha=0.5)
    ax.plot(r, gto_sum, color="C0", lw=2.4, label="Gaussian sum")
    ax.plot(r, sto, color="black", lw=2.0, ls="--", label=f"Slater (ζ = {zeta:.2f})")
    ax.axhline(0, color="gray", lw=0.8)
    ax.set_xlabel("r (Bohr)")
    ax.set_ylabel("amplitude")
    ax.set_xlim(0, 6)
    ax.legend(loc="upper right", fontsize=8)
    fig.tight_layout()
    st.pyplot(fig)
    plt.close(fig)

    m1, m2, m3 = st.columns(3)
    m1.metric("Shape overlap", f"{overlap * 100:.2f}%")
    m2.metric("φ(0) Slater", f"{sto[0]:.3f}")
    m3.metric("φ(0) Gaussians", f"{gto_sum[0]:.3f}")

    st.caption(
        "Watch two things the Gaussians struggle with. At r = 0 the Slater "
        "function has a sharp **cusp** (a finite slope into the nucleus), while "
        "every Gaussian is flat-topped — so the sum can't match the peak. And at "
        "large r the Gaussians die off as e^(−αr²), much faster than the Slater's "
        "e^(−ζr), so the tail falls short. Adding more Gaussians steadily improves "
        "the fit: that is the whole idea behind STO-nG basis sets."
        )
