import streamlit as st
import numpy as np
import py3Dmol

from pyscf import gto
from pyscf.dft import numint


# ==========================================================
# Streamlit helper
# ==========================================================

def showmol(view, height=700, width=900):
    st.components.v1.html(
        view._make_html(),
        height=height,
        width=width,
    )


# ==========================================================
# Cube generator
# ==========================================================

def make_cube_string(
    mol,
    values,
    nx,
    ny,
    nz,
    xmin,
    ymin,
    zmin,
    dx,
    dy,
    dz,
):
    """
    Generate Gaussian cube file contents as string.
    Coordinates are in Bohr.
    """

    lines = []

    lines.append("PySCF orbital")
    lines.append("Generated by Streamlit")

    lines.append(
        f"{mol.natm:5d}"
        f"{xmin:12.6f}"
        f"{ymin:12.6f}"
        f"{zmin:12.6f}"
    )

    lines.append(
        f"{nx:5d}"
        f"{dx:12.6f}"
        f"{0.0:12.6f}"
        f"{0.0:12.6f}"
    )

    lines.append(
        f"{ny:5d}"
        f"{0.0:12.6f}"
        f"{dy:12.6f}"
        f"{0.0:12.6f}"
    )

    lines.append(
        f"{nz:5d}"
        f"{0.0:12.6f}"
        f"{0.0:12.6f}"
        f"{dz:12.6f}"
    )

    for ia in range(mol.natm):

        z = mol.atom_charge(ia)
        xyz = mol.atom_coord(ia)

        lines.append(
            f"{z:5d}"
            f"{float(z):12.6f}"
            f"{xyz[0]:12.6f}"
            f"{xyz[1]:12.6f}"
            f"{xyz[2]:12.6f}"
        )

    flat = values.ravel(order="C")

    for i in range(0, len(flat), 6):

        chunk = flat[i:i + 6]

        lines.append(
            " ".join(
                f"{v:13.5e}"
                for v in chunk
            )
        )

    return "\n".join(lines)


# ==========================================================
# UI
# ==========================================================

st.title("Atomic Orbital Viewer")

default_xyz = """
O 0.000000 0.000000 0.000000
H 0.757000 0.586000 0.000000
H -0.757000 0.586000 0.000000
"""

xyz = st.text_area(
    "Molecule",
    default_xyz,
    height=120,
)

basis = st.text_input(
    "Basis set",
    "cc-pVDZ",
)

col1, col2, col3 = st.columns(3)

with col1:
    box = st.slider(
        "Box size (Bohr)",
        4.0,
        15.0,
        8.0,
    )

with col2:
    ngrid = st.slider(
        "Grid points",
        25,
        80,
        50,
    )

with col3:
    iso_frac = st.slider(
        "Isovalue fraction",
        min_value=0.001,
        max_value=0.1,
        step=0.00001,
        value=0.05
    )

# ==========================================================
# Molecule
# ==========================================================

try:

    mol = gto.M(
        atom=xyz,
        basis=basis,
        unit="Angstrom",
        verbose=0,
    )

except Exception as e:

    st.error(str(e))
    st.stop()

labels = mol.ao_labels()
nao = mol.nao_nr()

ao_idx = st.selectbox(
    "Atomic orbital",
    range(nao),
    format_func=lambda i:
    f"{i}: {labels[i]}"
)

# ==========================================================
# Grid
# ==========================================================

x = np.linspace(-box, box, ngrid)
y = np.linspace(-box, box, ngrid)
z = np.linspace(-box, box, ngrid)

X, Y, Z = np.meshgrid(
    x,
    y,
    z,
    indexing="ij",
)

coords = np.column_stack(
    [
        X.ravel(),
        Y.ravel(),
        Z.ravel(),
    ]
)

# ==========================================================
# Evaluate AO
# ==========================================================

with st.spinner("Evaluating orbital..."):

    ao = numint.eval_ao(
        mol,
        coords,
    )

orbital = ao[:, ao_idx]

volume = orbital.reshape(
    ngrid,
    ngrid,
    ngrid,
)

absmax = np.max(np.abs(volume))

iso = iso_frac * absmax

st.write(
    f"AO label: {labels[ao_idx]}"
)

st.write(
    f"AO range: "
    f"{volume.min():.3e} → {volume.max():.3e}"
)

st.write(
    f"Isovalue: {iso:.3e}"
)

# ==========================================================
# Cube string
# ==========================================================

cube_str = make_cube_string(
    mol,
    volume,
    ngrid,
    ngrid,
    ngrid,
    x[0],
    y[0],
    z[0],
    x[1] - x[0],
    y[1] - y[0],
    z[1] - z[0],
)

# ==========================================================
# Molecular geometry
# ==========================================================

xyz_block = f"{mol.natm}\n\n"

for ia in range(mol.natm):

    sym = mol.atom_symbol(ia)

    coord = mol.atom_coord(ia) * 0.52917721092

    xyz_block += (
        f"{sym} "
        f"{coord[0]:.6f} "
        f"{coord[1]:.6f} "
        f"{coord[2]:.6f}\n"
    )

# ==========================================================
# py3Dmol
# ==========================================================

view = py3Dmol.view(
    width=900,
    height=700,
)

view.addModel(
    xyz_block,
    "xyz",
)

view.setStyle(
    {},
    {
        "stick": {},
        "sphere": {"scale": 0.25},
    },
)

# positive phase

view.addVolumetricData(
    cube_str,
    "cube",
    {
        "isoval": iso,
        "color": "blue",
        "opacity": 0.75,
    },
)

# negative phase

view.addVolumetricData(
    cube_str,
    "cube",
    {
        "isoval": -iso,
        "color": "red",
        "opacity": 0.75,
    },
)

view.zoomTo()

showmol(view)
